# Generated by Django 5.2.7 on 2026-03-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.face')),
            ],
        ),
    ]
